spring:
  application:
    name: spock-test
  datasource:
    url: jdbc:mysql://localhost:3306/spock-test?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080

